extra:
    #
    # Change these macros if you wish to update the projects' name.
    # Use {{ variable_name }} in .md files to reference a variable that you've declared here.
    # For more information, read https://mkdocs-macros-plugin.readthedocs.io/en/latest/
    #
    project_name: Fosscord
    site_name: &site_name Fosscord Documentation
    repo_url: &repo_url https://github.com/fosscord/fosscord
    server_repo_url: https://github.com/fosscord/fosscord-Server
    client_repo_url: https://github.com/fosscord/fosscord-client
    edit_uri: &edit_uri https://github.com/fosscord/fosscord-docs/edit/master/docs/
    site_description: &site_description "Documentation for Fosscord: a free open source selfhostable chat, voice and video discord-compatible platform"
site_name: *site_name
repo_url: *repo_url
edit_uri: *edit_uri
site_description: *site_description
plugins:
    - section-index
    - search
    - macros
    - swagger-ui-tag:
          extra_css: [assets/swagger.css]
          docExpansion: none
          filter: true
theme:
    name: material
    logo: assets/logo.svg
    favicon: assets/favicon.svg
    font: Open Sans
    palette:
        - media: "(prefers-color-scheme: light)"
          primary: deep-orange
          scheme: default
          toggle:
              icon: material/lightbulb-outline
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: deep-orange
          scheme: slate
          toggle:
              icon: material/lightbulb
              name: Switch to light mode
    features:
        - navigation.expand
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - navigation.indexes
        - navigation.top
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
extra_css: [assets/extra.css]
